{% set name = "mkdocs-material-extensions" %}
{% set version = "1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_material_extensions-{{ version }}.tar.gz
  sha256: 96ca979dae66d65c2099eefe189b49d5ac62f76afb59c38e069ffc7cf3c131ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling>=0.21.1
    - pip
    - python >=3.7
  run:
    - python >=3.7
  run_constrained:
    - mkdocs-material >=5.0.0

test:
  source_files:
    - tests
  imports:
    - materialx
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - beautifulsoup4
    - pip
    - mkdocs-material >=5.0.0
    - pytest

about:
  home: https://github.com/facelessuser/mkdocs-material-extensions
  summary: Extension pack for Python Markdown
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dhirschfeld
    - marcelotrevisani
    - vallsv
    - dgasmith
    - thewchan
