{% set name = "mkdocs-material-extensions" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfd24dfdef7b41c312ede42648f9eb83476ea168ec163b613f9abd12bbfddba2

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
  run_constrained:
    - mkdocs-material >=5.0.0

test:
  imports:
    - materialx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocs-material-extensions/
  summary: Extension pack for Python Markdown
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - marcelotrevisani
    - vallsv
    - dgasmith
